[server]
port = 8501
enableCORS = false
headless = true
runOnSave = true

[theme]


base = "light"

primaryColor = "#4CAF50"  # Example green color


backgroundColor = "#FFFFFF" 

secondaryBackgroundColor = "#F0F0F5"  

textColor = "#000000"  # Black

font = "sans serif"

